# Generated by Django 6.0.2 on 2026-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_user_id', models.IntegerField()),
                ('server', models.CharField(default='SRGlobalFX-Live', max_length=100)),
                ('login_id', models.CharField(max_length=100)),
                ('account_type', models.CharField(default='MT5', max_length=20)),
                ('account_size', models.CharField(max_length=50)),
                ('plan_type', models.CharField(default='1-step', max_length=50)),
                ('profit_split', models.CharField(default='85%', max_length=20)),
                ('price_paid', models.CharField(default='0', max_length=50)),
                ('leverage', models.CharField(default='1:100', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('breached', 'Breached'), ('completed', 'Completed'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_user_id', models.IntegerField()),
                ('type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('submission_approved', 'Submission Approved'), ('submission_rejected', 'Submission Rejected'), ('account_created', 'Account Created'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
